export const PROTECTION_START_HOURS = 2;
export const DOSE_INTERVAL_HOURS = 24;
export const GRACE_PERIOD_HOURS = 6;
export const MAX_HISTORY_DAYS = 90;
export const LAPSES_AFTER_HOURS = DOSE_INTERVAL_HOURS + GRACE_PERIOD_HOURS;
